columnSuffix: null
handle: date
instructions: null
name: Date
searchable: false
settings:
  allDayMode: optional
  allowNeverEnding: true
translationKeyFormat: null
translationMethod: none
type: boundstate\eventful\fields\EventDate
